name: Show Secret
on: 
  workflow_call:
    inputs:
      var:
        description: "Secret"
        required: true
        type: string
    outputs:
      secret:
        value: ${{jobs.show.outputs}}
jobs:
  run-on: ubuntu-latest
  show:
    